apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.java.name }}
  namespace: {{ .Values.java.namespace }}
spec:
  type: {{ .Values.services.java.type }}
  selector:
    app: {{ .Values.java.selector }}
  ports:
  - protocol: {{ .Values.services.java.protocol }}
    port: {{ .Values.services.java.port }}
    targetPort: {{ .Values.java.sidecar.containerPort }}
