services:
  app:
    container_name: ${CONTAINER_NAME}
    build: .
    healthcheck:
      test: java -jar /*.jar | grep "Shoham" || exit 1
      interval: 2s
      timeout: 5s
      retries: 3
      start_period: 5s
