services:
  app:
    container_name: ${CONTAINER_NAME}
    build: .
    image: ${DOCKER_IMAGE}:${VERSION}
    healthcheck:
      test: java -jar /home/nonroot/*.jar | grep "Shoham" || exit 1
      interval: 2s
      timeout: 2s
      retries: 3
      start_period: 4s
