java:
  name: java-deployment
  namespace: java
  selector: java-app
  
  javaapp:
    name: hello-java
    image:
      name: "gingerous/javahello"
      tag:  "1.0.31"
    imagePullPolicy: Always

  sidecar:
    name: sidecar
    image:
      name: "gingerous/hellopython"
      tag: "latest"
    imagePullPolicy: Always
    containerPort: 8000

    readinessProbe:
      path: /ready
      port: 8000
      initialDelaySeconds: 15
      periodSeconds: 3

    livenessProbe:
      path: /health
      port: 8000
      initialDelaySeconds: 10
      periodSeconds: 5
      failureThreshold: 3

  imagePullSecrets: docker-cred

  nodeSelector:
    environment: java

  tolerations:
    key: env
    value: java
    effect: NoExecute


services:
  java:
    name: sidercar-service
    type: ClusterIP
    protocol: TCP
    port: 80


ingress:
  ingressClassName: nginx
  java:
    name: sidecar-ingress
    host: java.ginger-ous.click
    

strategy:
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%



replicaCount:
  java: 1
