name: Github Actions - Maven CI/CD
on:
  push:
    branches:
      - main
env:
  DOCKER_IMAGE: $DOCKER_IMAGE

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Increase patch
      run: |
        mvn -f myapp/pom.xml build-helper:parse-version versions:set -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.nextIncrementalVersion}'
        echo "VERSION=$(mvn -f myapp/pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
    
    - name: Compile
      run: mvn -f myapp/pom.xml compile

    - name: Package
      run: mvn -f myapp/pom.xml package

    - name: GitHub artifact
      uses: actions/upload-artifact@v4
      with:
        name: myapp-${{ env.VERSION }}
        path: myapp/target/*.jar

    - name: Build image
      run:  docker build -t ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE .
    
    - name: Test Image
      run: |
        output=$(docker run --rm ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE)

        if [[ "$output" != "Shoham wants to say Hello World!!!" ]]; then
            echo "the output isn't as expected"
            echo "the output is: $output"
            exit 1
        fi

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Publish docker image to Docker Hub
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE:${{ env.VERSION }}
        docker push ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE
        docker push ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE:${{ env.VERSION }}

    - name: Update pom.xml with new version
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GithubActions
        author_email: githubactions@ginger.com
        add: 'myapp/pom.xml'
        message: ${{ env.VERSION }}

  cd:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Pull latest docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE
          
      - name: Run & Test
        run: |
          output=$(docker run --rm ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE)
          
          if [[ "$output" != "Shoham wants to say Hello World!!!" ]]; then
            echo "the output isn't as expected"
            echo "the output is: $output"
            exit 1
          fi
