name: Github Actions - Maven CI/CD
on:
  push:
    branches:
      - test*

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout repository code
      uses: actions/checkout@v4

    - name: increase patch
      run: |
        mvn -f myapp/pom.xml build-helper:parse-version versions:set -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.nextIncrementalVersion}'
        echo "VERSION=$(mvn -f myapp/pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
    
    - name: compile
      run: mvn -f myapp/pom.xml compile

    - name: package
      run: mvn -f myapp/pom.xml package

    - name: GitHub artifact
      uses: actions/upload-artifact@v4
      with:
        name: myapp-${{ env.VERSION }}
        path: myapp/target/*.jar
