name: Github Actions - Maven CI/CD
on:
  push:
    branches:
      - test*

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout repository code
      uses: actions/checkout@v4

    - name: increase patch
      id: bump
      run: |
        mvn -f myapp/pom.xml build-helper:parse-version versions:set -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.nextIncrementalVersion}'
        cat myapp/pom.xml
